require("__dredgeworks__/prototypes/resources")
require("__dredgeworks__/prototypes/belt_flotation")
require("__dredgeworks__/prototypes/inserter_flotation")
require("__dredgeworks__/prototypes/technologies")
require("__dredgeworks__/prototypes/item")
require("__dredgeworks__/prototypes/recipe")